version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: react-hook-form
    versions:
    - 6.14.2
    - 6.15.1
    - 6.15.2
    - 6.15.3
    - 6.15.4
    - 6.15.5
    - 6.15.6
    - 7.0.0
    - 7.0.3
    - 7.0.4
    - 7.0.7
    - 7.2.0
    - 7.2.1
    - 7.2.3
    - 7.3.4
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
    - 12.6.3
    - 12.7.0
    - 12.7.1
    - 12.7.2
    - 12.7.3
    - 12.8.0
    - 12.8.1
    - 12.8.2
    - 12.8.3
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.14
    - 13.0.16
    - 13.0.2
    - 13.0.7
    - 13.0.8
    - 13.1.0
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.5
  - dependency-name: firebase-tools
    versions:
    - 9.2.2
    - 9.3.0
    - 9.4.0
    - 9.5.0
    - 9.6.0
    - 9.6.1
    - 9.7.0
    - 9.8.0
    - 9.9.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.12.0
    - 13.9.0
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: bl
    versions:
    - 4.0.3
